# Generated by Django 5.2.4 on 2025-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Economics', 'Economics'), ('Law', 'Law'), ('Politics', 'Politics'), ('Medicine', 'Medicine'), ('Aviation', 'Aviation')], max_length=100),
        ),
    ]
